### ISSUE TITLE
pardon my lurking

### ISSUE THREAD

**Issue by kylemac** [azmenak/reactivate#1]
i'm not sure if anyone else has reached out but we're super excited about anyone who is developing with roots + react. I'm wondering if you might want to join our #roots slack room? we'd love to trade the chance to pick your brain in exchange for being available for any questions you might have about roots (or anything else). let me know if you're interested.

**Comment by kylemac** [comment]
i guess i should also mention that this particular #roots slack room is the one where all the folks who work on roots hang out - including @jenius, the maintainer.

**Comment by jescalan** [comment]
:+1: :two_men_holding_hands:

**Comment by kylemac** [comment]
perhaps another time @azmenak !
